Set-Location "C:\Users\Sonia\Documents\FISCALIA antigo\WEBSITE\weconnectai"
$lines = @(
"function initNav(){var t=document.querySelector('.wc-nav-toggle');var l=document.querySelector('.wc-nav-links');if(!t||!l)return;t.addEventListener('click',function(){l.classList.toggle('open');});}"
"function initCookies(){var b=document.querySelector('.wc-cookies');if(!b)return;var d=localStorage.getItem('wc-cookies');if(d){b.classList.add('hidden');return;}b.classList.remove('hidden');var a=b.querySelector('[data-cookie-accept]');var x=b.querySelector('[data-cookie-decline]');if(a)a.addEventListener('click',function(){localStorage.setItem('wc-cookies','accept');b.classList.add('hidden');});if(x)x.addEventListener('click',function(){localStorage.setItem('wc-cookies','decline');b.classList.add('hidden');});}"
"window.wcSubmitLead=async function(form,source){if(!form)return false;var data=new FormData(form);var payload={access_key:'e29393bd-9c89-4ff0-af84-aeac777fd871',subject:'WeconnectAi lead',from_name:'WeconnectAi Site',replyto:data.get('email')||'',name:data.get('name')||'',email:data.get('email')||'',phone:data.get('phone')||'',topic:data.get('topic')||'',message:data.get('message')||'',source:source||'unknown',page:location.pathname,lang:getLang()};try{var response=await fetch('https://api.web3forms.com/submit',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});var result=await response.json();if(result.success){var ok=form.querySelector('.wc-lead-ok');if(!ok){ok=document.createElement('p');ok.className='wc-lead-ok';ok.style.cssText='color:#B6862C;font-weight:600;padding:12px;background:#F1E4CE;border-radius:4px;margin-top:10px;';ok.textContent='Obrigado!';form.appendChild(ok);}form.reset();}else{throw new Error(result.message||'err');}}catch(err){var ff=data.get('name')||data.get('email')||'web';var s='Lead - '+ff;var lines=[];data.forEach(function(v,k){if(v)lines.push(k+': '+v);});var b=encodeURIComponent(lines.join('\n'));window.location.href='mailto:geralfiscalia@proton.me?subject='+encodeURIComponent(s)+'&body='+b;}return false;};"
"window.wcCallAI=async function(sp,uc){var r=await fetch(ANTHROPIC_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'claude-sonnet-4-6',max_tokens:1200,system:sp,messages:[{role:'user',content:uc}]})});var d=await r.json();var t='';if(d&&d.content){for(var i=0;i<d.content.length;i++){if(d.content[i].text)t+=d.content[i].text+'\n';}}t=t.replace(/`json/g,'');t=t.replace(/`/g,'');return t.trim();};"
"window.wcStore={set:function(k,v){try{localStorage.setItem('wc:'+k,JSON.stringify({value:v,ts:Date.now()}));}catch(e){}},get:function(k){try{var r=localStorage.getItem('wc:'+k);if(!r)return null;var p=JSON.parse(r);return p&&p.value;}catch(e){return null;}},list:function(p){var o=[];try{for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf('wc:'+p)===0)o.push(k.substring(3));}}catch(e){}return o.sort().reverse();},delete:function(k){try{localStorage.removeItem('wc:'+k);}catch(e){}}};"
"document.addEventListener('DOMContentLoaded',function(){setLang(getLang());initNav();initCookies();var b=document.querySelectorAll('.wc-lang-btn');for(var i=0;i<b.length;i++){b[i].addEventListener('click',function(e){e.preventDefault();setLang(this.dataset.lang);});}});"
"document.addEventListener('DOMContentLoaded',function(){setLang(getLang());initNav();initCookies();var b=document.querySelectorAll('.wc-lang-btn');for(var i=0;i<b.length;i++){b[i].addEventListener('click',function(e){e.preventDefault();setLang(this.dataset.lang);});}});"
"document.addEventListener('DOMContentLoaded',function(){setLang(getLang());initNav();initCookies();var b=document.querySelectorAll('.wc-lang-btn');for(var i=0;i<b.length;i++){b[i].addEventListener('click',function(e){e.preventDefault();setLang(this.dataset.lang);});}});"
"document.addEventListener('DOMContentLoaded',function(){setLang(getLang());initNav();initCookies();var b=document.querySelectorAll('.wc-lang-btn');for(var i=0;i<b.length;i++){b[i].addEventListener('click',function(e){e.preventDefault();setLang(this.dataset.lang);});}});"
"document.addEventListener('DOMContentLoaded',function(){setLang(getLang());initNav();initCookies();var b=document.querySelectorAll('.wc-lang-btn');for(var i=0;i<b.length;i++){b[i].addEventListener('click',function(e){e.preventDefault();setLang(this.dataset.lang);});}});"
"document.addEventListener('DOMContentLoaded',function(){setLang(getLang());initNav();initCookies();var b=document.querySelectorAll('.wc-lang-btn');for(var i=0;i<b.length;i++){b[i].addEventListener('click',function(e){e.preventDefault();setLang(this.dataset.lang);});}});"
"document.addEventListener('DOMContentLoaded',function(){setLang(getLang());initNav();initCookies();var b=document.querySelectorAll('.wc-lang-btn');for(var i=0;i<b.length;i++){b[i].addEventListener('click',function(e){e.preventDefault();setLang(this.dataset.lang);});}});"
)
$lines | Out-File -Append -Encoding utf8 weconnectai.js
Write-Host "Parte 5 OK. Linhas:" (Get-Content weconnectai.js).Count