(function(){
'use strict';
var AI_PROXY_URL='https://weconnectai-ai-proxy.sonia-weconnectai.workers.dev';
var ANTHROPIC_URL=AI_PROXY_URL;
var S={pt:{},en:{}};
S.pt.nav={services:'Servicos',apps:'Apps gratuitas',about:'Sobre',contact:'Contacto',book:'Pedir orcamento'};
S.pt.hero={eyebrow:'Algarve - Portugal',title:'Pre-triagem e engenharia civil para o Algarve',lede:'Cinco apps gratuitas com IA.',cta_apps:'Experimentar as apps',cta_quote:'Pedir orcamento'};
S.pt.app={compliance:{num:'App 01',title:'Verificador de Conformidade',desc:'Cruze com o PDM.',cta:'Abrir'},feasibility:{num:'App 02',title:'Viabilidade',desc:'Posso construir aqui?',cta:'Abrir'},licensing:{num:'App 03',title:'Licenciamento',desc:'Acompanhe o processo.',cta:'Abrir'},renovation:{num:'App 04',title:'Renegociacao',desc:'Faixa EUR/m2.',cta:'Abrir'},energy:{num:'App 05',title:'Energetico',desc:'Faixa A+ a F.',cta:'Abrir'}};
S.pt.contact_section={eyebrow:'Contacto',title:'Fale-nos do seu projeto.',lead_h3:'Pedir orcamento',lead_p:'1 dia util.'};
S.pt.footer={tag:'Apps no Algarve.',copy:'2026 WeconnectAi',privacy:'Privacidade',terms:'Termos',apps_title:'Apps gratuitas',services_title:'Servicos',company_title:'Empresa'};
S.pt.form={project_params:'Parametros do projeto',municipality:'Municipio',parish:'Freguesia',parish_ph:'ex. Almancil',plot_area:'Area do terreno',intended_use:'Uso',use_residential:'Residencial',floor_area:'Area pavimento',height:'Altura',floors:'Pisos',setback_front:'Afastamento frente',setback_side:'Afastamento lateral',setback_rear:'Afastamento tardoz',ran_ren:'Estado RAN/REN',ran_no:'Fora RAN/REN',ran_hint:'Reserva Agricola/Ecologica',regulation_text:'Texto PDM',regulation_ph:'Cole clausulas',regulation_hint:'Precisao depende do texto',run_button:'Executar triagem',findings:'Resultados',empty_state:'Preencha parametros'};
S.pt.lead={review_title:'Quer um engenheiro a rever?',review_text:'Versao paga: verificacao completa.'};
S.en.nav={services:'Services',apps:'Free apps',about:'About',contact:'Contact',book:'Request a quote'};
S.en.hero={eyebrow:'Algarve - Portugal',title:'Pre-screening and civil engineering for the Algarve',lede:'Five free AI apps.',cta_apps:'Try the free apps',cta_quote:'Request a quote'};
S.en.app={compliance:{num:'App 01',title:'Algarve Compliance Checker',desc:'Cross-check PDM.',cta:'Open'},feasibility:{num:'App 02',title:'Land Feasibility',desc:'Can I build here?',cta:'Open'},licensing:{num:'App 03',title:'Licensing Navigator',desc:'Track camara process.',cta:'Open'},renovation:{num:'App 04',title:'Renovation Estimator',desc:'EUR/m2 range.',cta:'Open'},energy:{num:'App 05',title:'Energy Certificate',desc:'Class A+ to F.',cta:'Open'}};
S.en.contact_section={eyebrow:'Get in touch',title:'Tell us about your project.',lead_h3:'Request a quote',lead_p:'1 working day.'};
S.en.footer={tag:'Apps in the Algarve.',copy:'2026 WeconnectAi',privacy:'Privacy',terms:'Terms',apps_title:'Free apps',services_title:'Services',company_title:'Company'};
S.en.form={project_params:'Project parameters',municipality:'Municipality',parish:'Parish',parish_ph:'e.g. Almancil',plot_area:'Plot area',intended_use:'Intended use',use_residential:'Residential',floor_area:'Floor area',height:'Height',floors:'Floors',setback_front:'Setback front',setback_side:'Setback side',setback_rear:'Setback rear',ran_ren:'RAN/REN status',ran_no:'Not in RAN/REN',ran_hint:'National Agricultural/Ecological Reserve',regulation_text:'PDM text',regulation_ph:'Paste clauses',regulation_hint:'Accuracy depends on text',run_button:'Run screening',findings:'Findings',empty_state:'Fill parameters'};
S.en.lead={review_title:'Want a real engineer review?',review_text:'Paid version: full PDM check.'};
function getLang(){return localStorage.getItem('wc-lang')||'en';}
function setLang(l){localStorage.setItem('wc-lang',l);document.documentElement.lang=l;applyStrings(l);var b=document.querySelectorAll('.wc-lang-btn');for(var i=0;i<b.length;i++){b[i].classList.toggle('active',b[i].dataset.lang===l);}}
function gv(o,p){var ps=p.split('.');var v=o;for(var i=0;i<ps.length;i++){v=v&&v[ps[i]];}return typeof v==='string'?v:null;}
function applyStrings(l){var s=S[l];if(!s)return;var e=document.querySelectorAll('[data-i18n]');for(var i=0;i<e.length;i++){var v=gv(s,e[i].dataset.i18n);if(v)e[i].textContent=v;}var h=document.querySelectorAll('[data-i18n-html]');for(var j=0;j<h.length;j++){var v2=gv(s,h[j].dataset.i18nHtml);if(v2)h[j].innerHTML=v2;}var p=document.querySelectorAll('[data-i18n-ph]');for(var k=0;k<p.length;k++){var v3=gv(s,p[k].dataset.i18nPh);if(v3)p[k].setAttribute('placeholder',v3);}}
function initNav(){var t=document.querySelector('.wc-nav-toggle');var l=document.querySelector('.wc-nav-links');if(!t||!l)return;t.addEventListener('click',function(){l.classList.toggle('open');});}
function initCookies(){var b=document.querySelector('.wc-cookies');if(!b)return;var d=localStorage.getItem('wc-cookies');if(d){b.classList.add('hidden');return;}b.classList.remove('hidden');var a=b.querySelector('[data-cookie-accept]');var x=b.querySelector('[data-cookie-decline]');if(a)a.addEventListener('click',function(){localStorage.setItem('wc-cookies','accept');b.classList.add('hidden');});if(x)x.addEventListener('click',function(){localStorage.setItem('wc-cookies','decline');b.classList.add('hidden');});}
window.wcSubmitLead=async function(form,source){if(!form)return false;var data=new FormData(form);var payload={access_key:'e29393bd-9c89-4ff0-af84-aeac777fd871',subject:'WeconnectAi lead',from_name:'WeconnectAi Site',replyto:data.get('email')||'',name:data.get('name')||'',email:data.get('email')||'',phone:data.get('phone')||'',topic:data.get('topic')||'',message:data.get('message')||'',source:source||'unknown',page:location.pathname,lang:getLang()};try{var response=await fetch('https://api.web3forms.com/submit',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});var result=await response.json();if(result.success){var ok=form.querySelector('.wc-lead-ok');if(!ok){ok=document.createElement('p');ok.className='wc-lead-ok';ok.style.cssText='color:#B6862C;font-weight:600;padding:12px;background:#F1E4CE;border-radius:4px;margin-top:10px;';ok.textContent='Obrigado!';form.appendChild(ok);}form.reset();}else{throw new Error(result.message||'err');}}catch(err){var ff=data.get('name')||data.get('email')||'web';var s='Lead - '+ff;var lines=[];data.forEach(function(v,k){if(v)lines.push(k+': '+v);});var b=encodeURIComponent(lines.join('\n'));window.location.href='mailto:geralfiscalia@proton.me?subject='+encodeURIComponent(s)+'&body='+b;}return false;};
window.wcCallAI=async function(sp,uc){var r=await fetch(ANTHROPIC_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'claude-sonnet-4-6',max_tokens:1200,system:sp,messages:[{role:'user',content:uc}]})});var d=await r.json();var t='';if(d&&d.content){for(var i=0;i<d.content.length;i++){if(d.content[i].text)t+=d.content[i].text+'\n';}}t=t.split(String.fromCharCode(96)+String.fromCharCode(96)+String.fromCharCode(96)+'json').join('');t=t.split(String.fromCharCode(96)+String.fromCharCode(96)+String.fromCharCode(96)).join('');return t.trim();};
window.wcStore={set:function(k,v){try{localStorage.setItem('wc:'+k,JSON.stringify({value:v,ts:Date.now()}));}catch(e){}},get:function(k){try{var r=localStorage.getItem('wc:'+k);if(!r)return null;var p=JSON.parse(r);return p&&p.value;}catch(e){return null;}},list:function(p){var o=[];try{for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf('wc:'+p)===0)o.push(k.substring(3));}}catch(e){}return o.sort().reverse();},delete:function(k){try{localStorage.removeItem('wc:'+k);}catch(e){}}};
document.addEventListener('DOMContentLoaded',function(){setLang(getLang());initNav();initCookies();var b=document.querySelectorAll('.wc-lang-btn');for(var i=0;i<b.length;i++){b[i].addEventListener('click',function(e){e.preventDefault();setLang(this.dataset.lang);});}});
})();